CREATE TABLE Worker (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE Task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Content VARCHAR(255) NULL,
    Worker_Id INTEGER NULL,
    Work_in_progress BOOLEAN DEFAULT 0,
    To_review BOOLEAN DEFAULT 0,
    Done BOOLEAN DEFAULT 0,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Worker_Id) REFERENCES Worker(id)
);

CREATE TABLE Attendance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Worker_Id INTEGER NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Worker_Id) REFERENCES Worker(id)
);
